packages:
  - apps/*
  - packages/*

allowBuilds:
  '@crefle/web-ui@https://codeload.github.com/CREFLEINC/design-system-v2-webui/tar.gz/2891ae815853884120dfb647cb6674729ee2cede': true
  '@scarf/scarf': false
  esbuild: true
  node: true
